
package:
  name: caffe2
  version: {{ environ.get('PYTORCH_BUILD_VERSION') }}

source:
  path: ../../..

build:
  number: 0
  string: py{{py}}_{{ environ.get('PYTORCH_BUILD_DATE') }}
  skip: True  # [win]
  script_env:
    - CAFFE2_CMAKE_ARGS
    - PACKAGE_CUDA_LIBS
    - CUDA_VERSION
  # features section here

requirements:
  build:
    - cmake
    - future
    - numpy {{ numpy }}
    - python
    - setuptools
    - six
    # build section here
  run:
    - future
    - numpy
    - protobuf
    - python
    - setuptools
    - six
    # run section here

test:
  # test section here
  imports:
    - caffe2.python.core

about:
  home: https://caffe2.ai/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Caffe2 is a lightweight, modular, and scalable deep learning framework.

extra:
  recipe-maintainers:
    - pjh5
